### ISSUE TITLE
How to get first/last token in span

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/graphANNIS#84]
I'm testing the latest Kickstarter, which is great, but I have a scenario I can't get to work: 

I have a span annotation for entities with a pointing relation to the syntactic head token within it. I want to export all entity type annotations with head and first token, however, sometimes the head token is itself the head token. Things I've tried:

* Just query `span ->head tok` and CSV export, parse the first token out of covered text - this times out at 1000/30000 hits
* Query `span ->head tok & tok & #1 _l_ #3`. Now I can use frequencies, which is lightning fast (yay!), but if the head is span initial I don't get those hits due to the reflexivity constraint

Any ideas are appreciated - ideally I hope csvexport will be faster, but I could see users wanting to carry out something like query 2, which aql doesn't allow as of now

**Comment by thomaskrause** [comment]
>     * Just query `span ->head tok` and CSV export, parse the first token out of covered text - this times out at 1000/30000 hits

Ok, there should not be a timeout for the CSV exporter, even if it moves slowly and gets the results in slower pieces, having a timeout on a specific corpus for this kind of query might be a bug. Its weird that this does not affect the first matches, but that the timeout comes later on. It seems like sorting the results for the offset might be an issue here. Since the export needs to be performed on the whole result set anyway, the sorting could be removed. 
> 
>     * Query `span ->head tok & tok & #1 _l_ #3`. Now I can use frequencies, which is lightning fast (yay!), but if the head is span initial I don't get those hits due to the reflexivity constraint
> 
> 
> Any ideas are appreciated - ideally I hope csvexport will be faster, but I could see users wanting to carry out something like query 2, which aql doesn't allow as of now

The reflexivity constraint was only newly added to make AQL more sound for other corner cases (see https://github.com/korpling/ANNIS/issues/590). As a temporary workaround, you could go to the search options and select "Query Language" -> "AQL (compatibility mode)" to restore the old behavior and semantics. But we should think about an actual "same node" operator (not same text coverage) that could be used to explicitly "break" reflexivity constraints and allow the same node to be used. This operator does exist and used internally in query execution (`_ident_`). It is however not officially documented by purpose, because we never considered it as a part of AQL.

**Comment by amir-zeldes** [comment]
The timeout is strange then, although this is GUM, which is pretty stable in terms of data integrity (no empty tokens, weird disembodied nodes, segmentations etc.), even if it does have a ton of layers. I'd maybe wait to see if this is resolved in the stable graphANNIS release candidate. I definitely think CSVExporter needs to be faster to be useful in the future, especially since one of the goals of graphANNIS as I understand it is to allow for bigger corpora.

But I think the second question is more interesting: does anything speak against exposing the `_ident_` operator? TBH I'm a little surprised I've never needed it before, but in this scenario it seems intuitive that some users could need something like that.

**Comment by thomaskrause** [comment]
I think the `_ident_` operator was not mentioned, because it does not fit well in the "we search on attributes, not nodes" data model. With a more strict non-reflexivity constraint we might just want to add it to the list of documented operators. We also have a more defined data model via graphANNIS (https://korpling.github.io/graphANNIS/docs/v0.19/annotation-graph.html), where the semantics of the `_ident_` operator is more clear.

Did the `_ident_` operator solve you query problem? I just want to make sure I did not miss something in the definition **and implementation** which makes the desired behavior impossible even with this operator. Also, we should make sure that the current name is what we want, because it will be difficult/impossible to change it later.

**Comment by amir-zeldes** [comment]
Yes, I remember the discussions around searching for attributes, and I think that still the common understanding users have when using AQL, which is fine. I think this is really more of a power user feature, so I don't have a big issue with a 'clumsy' name like `_ident_`, but anything else is fine for me too. 

As for solving the problem, in the latest graphANNIS kickstarter I have, the AQL syntax highlighting doesn't parse `_ident_` correctly - it treats the operator as a third node and gives it a color, but other than that the implementation looks right! It's actually still quite tricky to get what I want, since if I enforce the ident, the cases without ident (i.e. where the head token and left most token are NOT the same) are lost, so I need a disjunction. This query does the trick, and requires named nodes for frequency analysis to work:

```
ent#entity ->head hd#tok & 
first#tok & 
#ent _l_ #first & 
#hd _ident_ #first 
| 
ent#entity ->head hd#tok & 
first#tok & 
#ent _l_ #first
```

But since this is a power-user feature, maybe this is fine. Only the syntax highlighting needs to be adjusted.

**Comment by thomaskrause** [comment]
Ok, I think it should be safe to just document the `_ident_` operator. I already updated the ANNIS feature branch to support the operator also in syntax highlighting.

If we don't like the representation of this operator, we could also think about grouping elements for the same attribute e.g. with brackets like
```
[pos="NN" & lemma="test"]
```
and use this as semantic sugar for
```
pos="NN" & lemma="test" & #1 _ident_ #2
```
This would be in line with the CQP syntax. In combination with metadata search using the `@*` operator (which works similar to `>*` but for "is part of a subcorpus/document" edges) such a clustering of `_ident_` using brackets could be quite useful, e.g.
```
tok @* [Genre="News" & Year=/195.*/]
```

**Comment by thomaskrause** [comment]
Also see  #88 for a pull request do deprecate `meta::` and use  `@*` per default instead.

**Comment by amir-zeldes** [comment]
I have no issues with the suggested operators, and I think in particular the option for grouping multiple meta-data items is essential, otherwise it will get very annoying to do:

```
tok @* genre="news" & #1 @* modality="tv" & #1 @* year=/20../
...
```

The only thing I don't understand is why eliminate the old syntax completely? I'm a fan of backward compatibility, so if the old `meta::genre="news"` can be internally re-written to `#1 @* genre="news"` then I'd be all for that.

One slightly unexpected result is that the same key name can be a metadatum and node annotation, so:

`sent _i_ type="news"`

is maybe some span annotation but

`sent @* type="news"`

implies that we're looking at a metadatum. In other words, the operator changes the meaning of the key, which is a little unexpected. But in practice this is unambiguous so probably fine. Could we keep backwards compatibility with `meta::...` though? Does anything speak against it?

**Comment by thomaskrause** [comment]
The problem is, that `meta::` only applies to documents, not sub-corpora and has some quite weird semantics in relANNIS. 

For existing queries, the quirks mode already addresses this by populating this to something like
`@* metaanno="..." _ident_ annis::doc`
Also, it was never clear whether in OR-queries the `meta::` clause is applied to a sub-clause or the whole match. In quirks mode I follow the semantics of relANNIS, which is actually quite odd (https://korpling.org/annis4-snapshot/VAADIN/help/aql-compatibility-mode.html#meta-data-constraints-are-applied-to-all-conjunctions-of-a-disjunction). Having these as normal attributes solves these "special treatment" problems

Old queries will always work in quirks mode (this is were I put most of the backwards-compatibility), but we should really think of the possible semantics of `meta::` in this more flexible solution. Also, I really like how this e.g. solves the whole "we need to have meta-attribute fields" in the UI (e.g. the frequency queries) even if there is technically no difference between metadata and "normal" annotations. One way we could redefine something like `meta::` would be annotations that should not be part of the output match (so emphasizing the "filter" character).  

I would argue to leave the `meta::` out in the beta-release, think about the proper semantics and add this or a similar concept later on when we are more sure what this means and how it is useful.

**Comment by amir-zeldes** [comment]
I agree with everything you say above about the more explicit solution being better, but I don't see why it needs to be left out, if it can be silently mapped on to a 'new' AQL structure deterministically. My attitude to this is generally 'the less alienation of current users the better' - there are always people who took some ANNIS tutorial somewhere who get upset when things don't work. 

I'd say leave it out of the documentation and just map it internally to `#1 @* metaanno="..." _ident_ annis::doc` as you suggested above. Not that it's critical or anything, but why not?

**Comment by thomaskrause** [comment]
> I agree with everything you say above about the more explicit solution being better, but I don't see why it needs to be left out, if it can be silently mapped on to a 'new' AQL structure deterministically. My attitude to this is generally 'the less alienation of current users the better' - there are always people who took some ANNIS tutorial somewhere who get upset when things don't work.

You are right about the "less friction", especially since also some example queries still use this syntax. I would propose to automatically switch (or ask the user if he wants to) to the compatibility mode whenever a deprecated syntax is detected, instead of only showing a syntax error (even if it has some explanation). This way its communicated clearly to the user that "don't use that in new queries". Still, they can access the query and try out thinks interactively without thinking about how to rewrite them manually. Not just documenting it might leave users asking why something works that is not documented. 

The proposed behavior is not yet part of 4.0.0-beta.1 because of time constraints, but I would like to implement it in one of the next betas and definitely before any final 4.0.0 release.

**Comment by amir-zeldes** [comment]
Wow, that would really be a 'deluxe' version of backwards compatibility. It sounds great, though if it's too much work I'm pretty sure users would be OK with a silent 'translation' as well.
